apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rc0faaxrw-dotnet-basic
  janus-idp.io/tekton: rc0faaxrw-dotnet-basic
  backstage.io/kubernetes-id: rc0faaxrw-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rc0faaxrw-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
